version: "3.8"

services:
  db1:
    image: postgres:15
    container_name: postgres-db1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  db2:
    image: postgres:15
    container_name: postgres-db2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: schooldb
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data: